/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppStoriesRouteImport } from './routes/app.stories'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPeopleRouteImport } from './routes/app.people'
import { Route as AppClsRouteImport } from './routes/app.cls'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppClsClassIdRouteImport } from './routes/app.cls.$classId'
import { Route as AppCConversationIdRouteImport } from './routes/app.c.$conversationId'
import { Route as AppClsClassIdIndexRouteImport } from './routes/app.cls.$classId.index'
import { Route as AppClsClassIdChannelSlugRouteImport } from './routes/app.cls.$classId.$channelSlug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStoriesRoute = AppStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppClsRoute = AppClsRouteImport.update({
  id: '/cls',
  path: '/cls',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppClsClassIdRoute = AppClsClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => AppClsRoute,
} as any)
const AppCConversationIdRoute = AppCConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => AppRoute,
} as any)
const AppClsClassIdIndexRoute = AppClsClassIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClsClassIdRoute,
} as any)
const AppClsClassIdChannelSlugRoute =
  AppClsClassIdChannelSlugRouteImport.update({
    id: '/$channelSlug',
    path: '/$channelSlug',
    getParentRoute: () => AppClsClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/cls': typeof AppClsRouteWithChildren
  '/app/people': typeof AppPeopleRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stories': typeof AppStoriesRoute
  '/app/': typeof AppIndexRoute
  '/app/c/$conversationId': typeof AppCConversationIdRoute
  '/app/cls/$classId': typeof AppClsClassIdRouteWithChildren
  '/app/cls/$classId/$channelSlug': typeof AppClsClassIdChannelSlugRoute
  '/app/cls/$classId/': typeof AppClsClassIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/cls': typeof AppClsRouteWithChildren
  '/app/people': typeof AppPeopleRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stories': typeof AppStoriesRoute
  '/app': typeof AppIndexRoute
  '/app/c/$conversationId': typeof AppCConversationIdRoute
  '/app/cls/$classId/$channelSlug': typeof AppClsClassIdChannelSlugRoute
  '/app/cls/$classId': typeof AppClsClassIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/cls': typeof AppClsRouteWithChildren
  '/app/people': typeof AppPeopleRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stories': typeof AppStoriesRoute
  '/app/': typeof AppIndexRoute
  '/app/c/$conversationId': typeof AppCConversationIdRoute
  '/app/cls/$classId': typeof AppClsClassIdRouteWithChildren
  '/app/cls/$classId/$channelSlug': typeof AppClsClassIdChannelSlugRoute
  '/app/cls/$classId/': typeof AppClsClassIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/cls'
    | '/app/people'
    | '/app/profile'
    | '/app/settings'
    | '/app/stories'
    | '/app/'
    | '/app/c/$conversationId'
    | '/app/cls/$classId'
    | '/app/cls/$classId/$channelSlug'
    | '/app/cls/$classId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/cls'
    | '/app/people'
    | '/app/profile'
    | '/app/settings'
    | '/app/stories'
    | '/app'
    | '/app/c/$conversationId'
    | '/app/cls/$classId/$channelSlug'
    | '/app/cls/$classId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/cls'
    | '/app/people'
    | '/app/profile'
    | '/app/settings'
    | '/app/stories'
    | '/app/'
    | '/app/c/$conversationId'
    | '/app/cls/$classId'
    | '/app/cls/$classId/$channelSlug'
    | '/app/cls/$classId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stories': {
      id: '/app/stories'
      path: '/stories'
      fullPath: '/app/stories'
      preLoaderRoute: typeof AppStoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cls': {
      id: '/app/cls'
      path: '/cls'
      fullPath: '/app/cls'
      preLoaderRoute: typeof AppClsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cls/$classId': {
      id: '/app/cls/$classId'
      path: '/$classId'
      fullPath: '/app/cls/$classId'
      preLoaderRoute: typeof AppClsClassIdRouteImport
      parentRoute: typeof AppClsRoute
    }
    '/app/c/$conversationId': {
      id: '/app/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/app/c/$conversationId'
      preLoaderRoute: typeof AppCConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cls/$classId/': {
      id: '/app/cls/$classId/'
      path: '/'
      fullPath: '/app/cls/$classId/'
      preLoaderRoute: typeof AppClsClassIdIndexRouteImport
      parentRoute: typeof AppClsClassIdRoute
    }
    '/app/cls/$classId/$channelSlug': {
      id: '/app/cls/$classId/$channelSlug'
      path: '/$channelSlug'
      fullPath: '/app/cls/$classId/$channelSlug'
      preLoaderRoute: typeof AppClsClassIdChannelSlugRouteImport
      parentRoute: typeof AppClsClassIdRoute
    }
  }
}

interface AppClsClassIdRouteChildren {
  AppClsClassIdChannelSlugRoute: typeof AppClsClassIdChannelSlugRoute
  AppClsClassIdIndexRoute: typeof AppClsClassIdIndexRoute
}

const AppClsClassIdRouteChildren: AppClsClassIdRouteChildren = {
  AppClsClassIdChannelSlugRoute: AppClsClassIdChannelSlugRoute,
  AppClsClassIdIndexRoute: AppClsClassIdIndexRoute,
}

const AppClsClassIdRouteWithChildren = AppClsClassIdRoute._addFileChildren(
  AppClsClassIdRouteChildren,
)

interface AppClsRouteChildren {
  AppClsClassIdRoute: typeof AppClsClassIdRouteWithChildren
}

const AppClsRouteChildren: AppClsRouteChildren = {
  AppClsClassIdRoute: AppClsClassIdRouteWithChildren,
}

const AppClsRouteWithChildren =
  AppClsRoute._addFileChildren(AppClsRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppClsRoute: typeof AppClsRouteWithChildren
  AppPeopleRoute: typeof AppPeopleRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStoriesRoute: typeof AppStoriesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCConversationIdRoute: typeof AppCConversationIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppClsRoute: AppClsRouteWithChildren,
  AppPeopleRoute: AppPeopleRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStoriesRoute: AppStoriesRoute,
  AppIndexRoute: AppIndexRoute,
  AppCConversationIdRoute: AppCConversationIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
